name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: sudo snap install --classic kotlin
      - run: ./adb-event-mirror.main.kts --test
